resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr:
  branches:
    exclude:
      - '*'
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure_ml/

variables:
- template: variable_template.yml
- group: aml_vg

pool:
  vmImage: ubuntu-latest


stages:
- stage: 'Write_Config_File'
  displayName: 'Write AML Config File'
  jobs:
  - job: "CONFIG_FILE"
    displayName: "Write AML Config File"
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $json = '{
          "subscription_id": "$(SUBSCRIPTION_ID)",
          "resource_group": "$(RESOURCE_GROUP)",
          "workspace_name": "$(WORKSPACE_NAME)"
          }'
            
          $json | Out-File config.json
        workingDirectory: $(Build.SourcesDirectory)/$(PIPELINE_DIR)
- stage: 'Publish_AML_Pipeline'
  displayName: 'Publish AML Pipeline'
  jobs:
  - job: "AML_PIPELINE"
    displayName: "Build and Publish AML Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)/$(PIPELINE_DIR)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a training pipeline
          python -m create_aml_pipeline
      displayName: 'Publish Azure Machine Learning Pipeline'